# 伐木工，矿工，烧炼师，农场主，牧场主，怪物猎人，糕点师，工具制造商
allowed_abilities:
  - "generic.lumberjack"
  - "generic.builder"
  - "generic.miner"
  - "generic.mechanic"
  - "generic.explosive"
  - "generic.musician"
  - "generic.smelter"
  - "generic.farmer"
  - "generic.rancher"
  - "generic.hunter"
  - "generic.monster_hunter"
  - "generic.fisherman"
  - "generic.dye"
  - "generic.railway_engineer"
  - "generic.tamer"
  - "generic.enchanter"
  - "generic.artisan"
  - "generic.brewer"
  - "generic.confectioner"
  - "generic.tool_maker"