name: StarLightCoreX
version: '${version}'
main: io.hikarilan.starlightcorex.StarLightCoreX
api-version: 1.18
authors: [ HikariLan ]
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlin_version}
  - org.jetbrains.kotlin:kotlin-stdlib-common:${kotlin_version}
  - org.jetbrains.kotlin:kotlin-stdlib-jdk7:${kotlin_version}
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlin_version}
  - org.jetbrains.kotlin:kotlin-reflect:${kotlin_version}